### ISSUE TITLE
Name of vehicle

### ISSUE THREAD

**Issue by Laurynas23** [TanguyOrtegat/jb_vehiclelock#1]
hi im just finking is it possible change GetLabelText(GetDisplayNameFromVehicleModel(GetEntityModel(vehicle)))
to something another , lets say im thinkinghow to set this message read not vehicle model name but read plate number, and when you lock/unlock its pop up whit plate number.
if some 1 can do i will be more than happy.
Thanks

**Comment by TanguyOrtegat** [comment]
the script is working, if you want plate instead of vehicle name you are free to go to edit the script in on your server :)
